version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8001:8000"
    environment:
      - DEBUG=True
      - DATABASE_URL=postgresql://portfolio:password@db:5432/portfolio_db
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    ports:
      - "3030:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8001

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=portfolio_db
      - POSTGRES_USER=portfolio
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
